version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: photogram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s9td3ixh
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume: